/**
 * This file was automatically generated by Leao.
 * Any modifications made will be discarded.
 */
import colorPicker from "@leao1/plugin-color-picker/leao-admin";
import documentation from "@leao1/plugin-documentation/leao-admin";
import graphql from "@leao1/plugin-graphql/leao-admin";
import usersPermissions from "@leao1/plugin-users-permissions/leao-admin";
import myplugin from "../../src/plugins/local-plugin/leao-admin";
import { renderAdmin } from "@leao1/leao/admin";

import customisations from "../../src/admin/app.jsx";

renderAdmin(document.getElementById("leao"), {
  customisations,
  features: { future: { preview: false } },
  plugins: {
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    "users-permissions": usersPermissions,
    myplugin: myplugin,
  },
});
