/**
 * This file was automatically generated by Leao.
 * Any modifications made will be discarded.
 */
import documentation from "@leao/plugin-documentation/leao-admin";
import usersPermissions from "@leao/plugin-users-permissions/leao-admin";
import { renderAdmin } from "@leao/leao/admin";

renderAdmin(document.getElementById("leao"), {
  plugins: {
    documentation: documentation,
    "users-permissions": usersPermissions,
  },
});
